# Generated by Django 2.2.10 on 2020-09-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=30)),
                ('pillname', models.CharField(max_length=30)),
                ('pilldosage', models.CharField(max_length=100)),
                ('userpw', models.CharField(max_length=10)),
            ],
        ),
    ]
