version: '3.5'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/django
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes: 
      - ./:/django/
    expose:
      - "8000"
